import {expect,it,vi} from 'vitest';
import {verifyOperations} from '../server/briefVerifier';
import {createBriefState,applyBriefOperations} from '../shared/briefState';
import type {BriefOperation} from '../shared/briefSchema';
const hoop:BriefOperation={type:'replace',factIds:['bold-earrings'],fact:{id:'hoop',field:'style',value:{kind:'facet',attribute:'Catalog_EarringType',values:['Hoop'],operator:'any'},scope:{kind:'item',key:'earrings'},strength:'requirement',status:'active',origin:'spoken',evidence:{messageId:'m2',quote:'make the earrings hoops',explicit:true,verified:false}}};
async function verify(verdict:Record<string,boolean|undefined>,operation:BriefOperation=hoop){return verifyOperations(vi.fn().mockResolvedValue({verdicts:[{operationIndex:0,...verdict}]}),{},[operation],AbortSignal.timeout(1000));}
it('activates a verified hoop addition without authorizing deletion of compatible bold styling',async()=>{const [result]=await verify({entailed:false,unambiguous:false,factEntailed:true,factUnambiguous:true});expect(result).toMatchObject({type:'add',fact:{status:'active',evidence:{verified:true}}});expect(result).not.toHaveProperty('factIds');const original=applyBriefOperations(createBriefState('mission'),{missionId:'mission',expectedRevision:0,turnId:'m1',operations:[{type:'add',fact:{...hoop.fact,id:'bold-earrings',value:{kind:'text',text:'bold'},strength:'preference',evidence:{messageId:'m1',quote:'bold earrings',explicit:true,verified:true}}}]});const next=applyBriefOperations(original,{missionId:'mission',expectedRevision:1,turnId:'m2',operations:[result]});expect(next.facts.map(f=>({id:f.id,status:f.status}))).toEqual([{id:'bold-earrings',status:'active'},{id:'hoop',status:'active'}]);});
it('keeps ambiguous new meaning tentative and preserves every target',async()=>{const [result]=await verify({entailed:false,unambiguous:false,factEntailed:false,factUnambiguous:false});expect(result).toMatchObject({type:'add',fact:{status:'tentative',evidence:{verified:false}}});});
it('rejects inconsistent positive operation verdict when separate fact meaning is false or incomplete',async()=>{for(const verdict of [{factEntailed:false,factUnambiguous:true},{factEntailed:true}]){const [result]=await verify({entailed:true,unambiguous:true,...verdict});expect(result).toMatchObject({type:'add',fact:{status:'tentative'}});}});
it('allows a fully verified exact budget replacement',async()=>{const budget:BriefOperation={...hoop,factIds:['old-budget'],fact:{...hoop.fact,id:'new-budget',field:'budget',value:{kind:'money',cents:7500,currency:'USD',operator:'lt',basis:'per-item'},scope:{kind:'mission'},evidence:{...hoop.fact.evidence,quote:'make it under $75 per item'}}};const [result]=await verify({entailed:true,unambiguous:true,factEntailed:true,factUnambiguous:true},budget);expect(result).toMatchObject({type:'replace',factIds:['old-budget'],fact:{status:'active'}});});
it('retains conservative legacy behavior when fact verdicts are absent',async()=>{expect((await verify({entailed:false,unambiguous:false}))[0]).toMatchObject({type:'add',fact:{status:'tentative'}});});
it('requires clarification when an unauthorized replacement would leave an older same-scope budget in force',async()=>{const old={...hoop.fact,id:'old-budget',field:'budget' as const,value:{kind:'money' as const,cents:10000,currency:'USD' as const,operator:'lte' as const,basis:'per-item' as const},scope:{kind:'mission' as const}};const replacement:BriefOperation={type:'replace',factIds:['old-budget'],fact:{...old,id:'new-budget',value:{...old.value,cents:20000}}};const model=vi.fn().mockResolvedValue({verdicts:[{operationIndex:0,entailed:false,unambiguous:false,factEntailed:true,factUnambiguous:true}]});const [result]=await verifyOperations(model,{currentBrief:{facts:[old]}},[replacement],AbortSignal.timeout(1000));expect(result).toMatchObject({type:'add',fact:{status:'tentative',evidence:{verified:true}}});const [separate]=await verifyOperations(model,{currentBrief:{facts:[{...old,value:{...old.value,basis:'total'}}]}},[replacement],AbortSignal.timeout(1000));expect(separate).toMatchObject({type:'add',fact:{status:'active'}});});
it('clarifies direct hard-facet contradictions but permits ProductType alternatives',async()=>{const old={...hoop.fact,id:'no-silver',value:{kind:'facet' as const,attribute:'Catalog_JewelryMaterialNavigationName',values:['Silver'],operator:'none' as const}};const addition:BriefOperation={type:'replace',factIds:['unrelated'],fact:{...old,id:'silver',value:{...old.value,operator:'any'}}};const model=vi.fn().mockResolvedValue({verdicts:[{operationIndex:0,entailed:false,unambiguous:false,factEntailed:true,factUnambiguous:true}]});expect((await verifyOperations(model,{currentBrief:{facts:[old]}},[addition],AbortSignal.timeout(1000)))[0]).toMatchObject({type:'add',fact:{status:'tentative'}});const necklace={...old,value:{kind:'facet' as const,attribute:'Catalog_ProductType',values:['Necklace'],operator:'any' as const}};const earrings:BriefOperation={type:'add',fact:{...addition.fact,value:{...necklace.value,values:['Earrings']}}};expect((await verifyOperations(model,{currentBrief:{facts:[necklace]}},[earrings],AbortSignal.timeout(1000)))[0]).toMatchObject({type:'add',fact:{status:'active'}});});
it('allows verified new-mission facts after a verified reset despite old exclusions',async()=>{const old={...hoop.fact,id:'no-gold',value:{kind:'facet' as const,attribute:'Catalog_JewelryMaterialNavigationName',values:['Gold'],operator:'none' as const}};const gold:BriefOperation={type:'add',fact:{...old,id:'new-gold',value:{...old.value,operator:'any'}}};const reset:BriefOperation={type:'reset-brief',evidence:{messageId:'m2',quote:'A separate gift in gold',explicit:true,verified:false}};const model=vi.fn().mockResolvedValue({verdicts:[{operationIndex:0,entailed:true,unambiguous:true},{operationIndex:1,entailed:true,unambiguous:true,factEntailed:true,factUnambiguous:true}]});const result=await verifyOperations(model,{currentBrief:{facts:[old]}},[reset,gold],AbortSignal.timeout(1000));expect(result[0]).toMatchObject({type:'reset-brief',evidence:{verified:true}});expect(result[1]).toMatchObject({type:'add',fact:{status:'active'}});});
