import {afterEach,expect,it,vi} from 'vitest';
import {createApiServer} from '../server/api';
import {createBriefState} from '../shared/briefState';
const servers:ReturnType<typeof createApiServer>[]=[];
afterEach(async()=>{await Promise.all(servers.splice(0).map(s=>new Promise<void>(resolve=>s.close(()=>resolve()))));});
const state=createBriefState('mission-1');
const input={id:'conversation-1',messages:[{id:'m1',role:'user',parts:[{type:'text',text:'Hello'}]}],shoppingBrief:{state,turnId:'m1'}};
async function setup(model=vi.fn().mockResolvedValue({operations:[]}),telemetryLogger=vi.fn()){
 const upstream=vi.fn(async(_url:string|URL|Request,_init?:RequestInit)=>new Response('data: {"type":"start","messageId":"a"}\n\ndata: {"type":"finish"}\n\ndata: [DONE]\n\n'));
 const server=createApiServer({appId:'TEST123',apiKey:'secret',fetch:upstream,briefModel:model,briefV2Enabled:true,telemetryLogger});servers.push(server);await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;
 return {model,upstream,post:(payload:unknown)=>fetch(`http://127.0.0.1:${port}/api/chat`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})};
}
it('fails closed without brief or on failed interpretation; never calls concierge',async()=>{const s=await setup(vi.fn().mockRejectedValue(new Error('timeout')));const {shoppingBrief,...legacy}=input;expect((await s.post(legacy)).status).toBe(400);const result=await s.post(input);expect(result.status).toBe(503);expect(await result.json()).toMatchObject({code:'BRIEF_RETRY'});expect(s.upstream).not.toHaveBeenCalled();expect(shoppingBrief.state.revision).toBe(0);});
it('tags revision and request before SDK stream and preserves client tool continuation parts',async()=>{const s=await setup();const response=await s.post(input);expect(response.status).toBe(200);expect(response.headers.get('server-timing')).toContain('interpret');const output=await response.text();const event=JSON.parse(output.split('\n').find(line=>line.includes('data-shopping-brief'))!.slice(6));expect(event.data).toMatchObject({missionId:'mission-1',baseRevision:0,revision:1,turnId:'m1'});const continuation={...input,shoppingBrief:{state:event.data.state,turnId:'m1'},messages:[...input.messages,{id:'a',role:'assistant',parts:[{type:'tool-clientLookup',toolCallId:'call1',state:'output-available',input:{id:'item1'},output:{ok:true}}]}]};await(await s.post(continuation)).text();expect(s.model).toHaveBeenCalledTimes(1);const payload=JSON.parse(s.upstream.mock.calls[1]![1]!.body as string);expect(payload.messages.at(-1).parts[0].toolCallId).toBe('call1');expect(payload.shoppingBrief).toBeUndefined();expect(payload.messages[0].metadata.turnContext.briefRevision).toBe('1');});
it('request revision markers let a concurrently edited client reject old results',async()=>{const s=await setup();const response=await s.post(input);const output=await response.text();expect(output).toContain('"baseRevision":0');expect(output).toContain('"revision":1');expect(state.revision).toBe(0);});
it('uncertain budget streams a clarification and brief without any concierge search',async()=>{const fact={id:'b1',field:'budget',value:{kind:'money',cents:20000,currency:'USD',operator:'lt',basis:'unresolved'},scope:{kind:'mission'},strength:'requirement',status:'tentative',origin:'spoken',evidence:{messageId:'m1',quote:'Under $200',explicit:false,verified:false}};const model=vi.fn().mockResolvedValueOnce({operations:[{type:'add',fact}]}).mockResolvedValueOnce({verdicts:[{operationIndex:0,entailed:true,unambiguous:false}]}).mockResolvedValueOnce({question:'Is that for both pieces together?'});const s=await setup(model);const response=await s.post({...input,messages:[{id:'m1',role:'user',parts:[{type:'text',text:'Under $200'}]}]});const output=await response.text();expect(output).toContain('both pieces together');expect(output).toContain('data-shopping-brief');expect(output).toContain('[DONE]');expect(s.upstream).not.toHaveBeenCalled();});

it('logs a bounded metadata snapshot on failure without text or provider error',async()=>{const logger=vi.fn();const s=await setup(vi.fn().mockRejectedValue(new Error('PRIVATE-provider-secret')),logger);const response=await s.post({...input,messages:[{id:'m1',role:'user',parts:[{type:'text',text:'PRIVATE-shopper-text'}]}]});await response.text();expect(logger).toHaveBeenCalledTimes(1);const log=logger.mock.calls[0][0];expect(log).toMatchObject({event:'jtv_request',turnId:'m1',statusCode:503,completed:true});expect(JSON.stringify(log)).not.toContain('PRIVATE');expect(log.phases).toHaveProperty('interpret');});
it('does not let agreeing models activate unresolved money or start concierge retrieval',async()=>{const fact={id:'b1',field:'budget',value:{kind:'money',cents:18000,currency:'USD',operator:'lte',basis:'unresolved'},scope:{kind:'mission'},strength:'requirement',status:'active',origin:'spoken',evidence:{messageId:'m1',quote:'My budget is $180',explicit:true,verified:false}};const model=vi.fn().mockResolvedValueOnce({operations:[{type:'add',fact}]}).mockResolvedValueOnce({verdicts:[{operationIndex:0,entailed:true,unambiguous:true}]}).mockResolvedValueOnce({question:'Is that $180 for both pieces together?'});const s=await setup(model);const response=await s.post({...input,messages:[{id:'m1',role:'user',parts:[{type:'text',text:'My budget is $180'}]}]});const text=await response.text();expect(text).toContain('both pieces together');const event=JSON.parse(text.split('\n').find(line=>line.includes('data-shopping-brief'))!.slice(6));expect(event.data.state.facts[0].status).toBe('tentative');expect(event.data.appliedFactIds).toEqual([]);expect(s.upstream).not.toHaveBeenCalled();});
it('does not search under an older stricter budget after a partially verified correction',async()=>{const {applyBriefOperations}=await import('../shared/briefState');const old={id:'old100',field:'budget' as const,value:{kind:'money' as const,cents:10000,currency:'USD' as const,operator:'lte' as const,basis:'per-item' as const},scope:{kind:'mission' as const},strength:'requirement' as const,status:'active' as const,origin:'ui' as const,evidence:{messageId:'ui',quote:'$100',explicit:true,verified:true}};const prior=applyBriefOperations(state,{missionId:state.missionId,expectedRevision:0,turnId:'ui',operations:[{type:'add',fact:old}]});const model=vi.fn().mockResolvedValueOnce({operations:[{type:'replace',factIds:['old100'],fact:{...old,id:'new200',origin:'spoken',value:{...old.value,cents:20000},evidence:{messageId:'m1',quote:'Change the limit to $200 per item',explicit:true,verified:false}}}]}).mockResolvedValueOnce({verdicts:[{operationIndex:0,entailed:false,unambiguous:false,factEntailed:true,factUnambiguous:true}]}).mockResolvedValueOnce({question:'Should the $200 limit replace your earlier $100 limit?'});const s=await setup(model);const response=await s.post({...input,shoppingBrief:{state:prior,turnId:'m1'},messages:[{id:'m1',role:'user',parts:[{type:'text',text:'Change the limit to $200 per item'}]}]});const text=await response.text();expect(text).toContain('earlier $100');expect(text).toContain('"status":"tentative"');expect(s.upstream).not.toHaveBeenCalled();});
