import {afterEach,it,expect,vi} from 'vitest';
import {createApiServer} from '../server/api';
const servers:ReturnType<typeof createApiServer>[]=[];
afterEach(async()=>{await Promise.all(servers.splice(0).map(s=>new Promise<void>(r=>s.close(()=>r()))));});
async function setup(result:unknown={proposals:[{field:'material',value:'silver',quote:'silver',messageId:'m1'}]}){const extractor=vi.fn(async()=>result);const upstream=vi.fn();const server=createApiServer({appId:'TEST123',apiKey:'secret',fetch:upstream,briefExtractor:extractor});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const port=(server.address() as {port:number}).port;return {extractor,upstream,post:(input:unknown,origin='http://localhost:5173')=>fetch(`http://127.0.0.1:${port}/api/brief`,{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(input)})};}
const input={missionId:'mission-1',messages:[{id:'m1',text:'silver please'}]};
it('returns tentative, provenance-validated facts without touching catalogue',async()=>{const s=await setup();const response=await s.post(input);expect(response.status).toBe(200);expect((await response.json()).proposals[0]).toMatchObject({status:'proposed',quote:'silver'});expect(s.upstream).not.toHaveBeenCalled();});
it('blocks foreign origin, role smuggling, duplicate IDs and config overrides',async()=>{const s=await setup();expect((await s.post(input,'https://evil.example')).status).toBe(403);for(const data of [{...input,configuration:{}},{...input,messages:[{id:'m1',role:'assistant',text:'silver'}]},{...input,messages:[input.messages[0],input.messages[0]]}])expect((await s.post(data)).status).toBe(400);expect(s.extractor).not.toHaveBeenCalled();});
it('makes extraction failures visible instead of fabricating or returning ungrounded facts',async()=>{const s=await setup({proposals:[{field:'material',value:'gold',quote:'gold',messageId:'m1'}]});const response=await s.post(input);expect(response.status).toBe(502);expect((await response.json()).error).toContain('keep chatting');});

it('uses only server-owned published extractor identity and no configuration override',async()=>{
 const {createNativeBriefExtractor}=await import('../server/brief');
 const upstream=vi.fn(async()=>new Response('data: '+JSON.stringify({type:'text-delta',delta:JSON.stringify({proposals:[{field:'material',value:'silver',quote:'silver',messageId:'m1'}]})})+'\n\ndata: [DONE]\n\n'));
 const result=await createNativeBriefExtractor({appId:'TEST123',apiKey:'secret',fetch:upstream,briefAgentId:'extractor-123'})(input,AbortSignal.timeout(1000));
 expect(result).toMatchObject({proposals:[{field:'material'}]});
 const args=upstream.mock.calls[0] as unknown as [string,RequestInit];const payload=JSON.parse(args[1].body as string);
 expect(payload.configuration).toBeUndefined();expect(args[0]).toContain('/extractor-123/completions');expect(args[0]).toContain('memory=false');expect(payload.messages).toHaveLength(1);
});

it('returns configuration-specific 503 without an upstream call when extractor absent',async()=>{const upstream=vi.fn();const server=createApiServer({appId:'TEST123',apiKey:'secret',fetch:upstream});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const port=(server.address() as {port:number}).port;const response=await fetch(`http://127.0.0.1:${port}/api/brief`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});expect(response.status).toBe(503);expect((await response.json()).error).toContain('not configured');expect(upstream).not.toHaveBeenCalled();});
it('regenerates once on malformed model JSON using original input, with retry metadata',async()=>{const {createNativeBriefModel}=await import('../server/brief');const event=(text:string)=>new Response('data: '+JSON.stringify({type:'text-delta',delta:text})+'\n\ndata: {"type":"finish"}\n\n');const upstream=vi.fn().mockResolvedValueOnce(event('{"operations":[{"type":"add"}')).mockResolvedValueOnce(event('{"operations":[]}'));const retry=vi.fn();const model=createNativeBriefModel({appId:'TEST123',apiKey:'secret',fetch:upstream,briefAgentId:'extractor-123',onFormatRetry:retry});expect(await model({phase:'INTERPRET',input:{latestMessage:'original evidence'}},AbortSignal.timeout(1000))).toEqual({operations:[]});const second=JSON.parse(JSON.parse(upstream.mock.calls[1][1].body).messages[0].parts[0].text);expect(second).toMatchObject({phase:'INTERPRET',input:{latestMessage:'original evidence'}});expect(second.formatCorrection).toContain('complete response');expect(retry).toHaveBeenCalledWith(expect.objectContaining({phase:'INTERPRET',success:true,firstFailure:'json_syntax'}));});
it('fails after a second malformed JSON response and never retries upstream/tool errors',async()=>{const {createNativeBriefModel}=await import('../server/brief');const response=()=>new Response('data: {"type":"text-delta","delta":"{"}\n\n');const upstream=vi.fn().mockImplementation(response);const retry=vi.fn();await expect(createNativeBriefModel({appId:'TEST123',apiKey:'secret',fetch:upstream,briefAgentId:'extractor-123',onFormatRetry:retry})({phase:'INTERPRET'},AbortSignal.timeout(1000))).rejects.toThrow(SyntaxError);expect(upstream).toHaveBeenCalledTimes(2);expect(retry).toHaveBeenCalledWith(expect.objectContaining({success:false}));const failed=vi.fn().mockResolvedValue(new Response('unavailable',{status:503}));await expect(createNativeBriefModel({appId:'TEST123',apiKey:'secret',fetch:failed,briefAgentId:'extractor-123'})({phase:'INTERPRET'},AbortSignal.timeout(1000))).rejects.toThrow('unavailable');expect(failed).toHaveBeenCalledTimes(1);});
it('retains the last SSE text frame even without a trailing newline',async()=>{const {createNativeBriefModel}=await import('../server/brief');const upstream=vi.fn().mockResolvedValue(new Response('data: '+JSON.stringify({type:'text-delta',delta:'{"operations":[]}'})));expect(await createNativeBriefModel({appId:'TEST123',apiKey:'secret',fetch:upstream,briefAgentId:'extractor-123'})({phase:'INTERPRET'},AbortSignal.timeout(1000))).toEqual({operations:[]});expect(upstream).toHaveBeenCalledTimes(1);});
