import {afterEach,describe,it,expect,vi} from 'vitest';
import {beginTrace,clientTraces,observeTrace,workspaceTraceForTool,markWorkspace,markWorkspaceImage,type WorkspaceTraceBinding} from '../src/telemetry';
afterEach(()=>{clientTraces.length=0;vi.restoreAllMocks()});
function setup(){vi.spyOn(performance,'now').mockReturnValue(1000);const trace=beginTrace('turn','mission');const binding:WorkspaceTraceBinding={requestId:trace.requestId,turnId:'turn',missionId:'mission',revision:2};return {trace,binding}}
describe('request-correlated workspace telemetry',()=>{
 it('uses tool identity to distinguish continuation requests within one turn',()=>{const {trace}=setup();observeTrace(trace,{type:'tool-input-available',toolCallId:'first'},20);const second=beginTrace('turn','mission');observeTrace(second,{type:'tool-input-available',toolCallId:'second'},30);expect(workspaceTraceForTool('turn','first')).toBe(trace);expect(workspaceTraceForTool('turn','second')).toBe(second);expect(workspaceTraceForTool('turn','unknown')).toBeUndefined()});
 it('records bounded monotonic commit, observed paint and image outcomes without image identity',()=>{const {trace,binding}=setup();vi.spyOn(Date,'now').mockReturnValue(1);markWorkspace(binding,'commit',3,1150);markWorkspace(binding,'commit',3,1160);markWorkspace(binding,'paint-observed',3,1180);markWorkspaceImage(binding,'private-image-url','loaded',1200);markWorkspaceImage(binding,'private-image-url','loaded',1201);markWorkspaceImage(binding,'second-url','failed',1220);expect(trace.events).toEqual([{type:'workspace_commit',ms:150,revision:2,count:3},{type:'workspace_paint-observed',ms:180,revision:2,count:3},{type:'workspace_image',ms:200,revision:2,outcome:'loaded'},{type:'workspace_image',ms:220,revision:2,outcome:'failed'}]);expect(JSON.stringify(trace)).not.toContain('url')});
 it('ignores wrong mission, request, turn and empty workspace events',()=>{const {trace,binding}=setup();for(const bad of [{...binding,missionId:'old'},{...binding,requestId:'old'},{...binding,turnId:'old'}]){markWorkspace(bad,'commit',3);markWorkspaceImage(bad,'image','loaded')}markWorkspace(binding,'commit',0);expect(trace.events).toEqual([])});
 it('caps image observations and retained traces',()=>{const {trace,binding}=setup();for(let i=0;i<130;i++)markWorkspaceImage(binding,String(i),'loaded',1100+i);expect(trace.events).toHaveLength(100);for(let i=0;i<60;i++)beginTrace(String(i),'mission');expect(clientTraces).toHaveLength(50)});
});

it('preserves a failed upstream outcome after the protocol finish event without logging error text',()=>{const {trace}=setup();observeTrace(trace,{type:'error',errorText:'PRIVATE'},50);observeTrace(trace,{type:'finish'},60);expect(trace.termination).toBe('failed');expect(trace.streamCompletionMs).toBe(60);expect(trace.events.map(e=>e.type)).toEqual(['error','finish']);expect(JSON.stringify(trace)).not.toContain('PRIVATE')});
