// Distinct view contracts: comparison isn't a basket; combination arithmetic is explicit; images are real records.
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {it,expect,vi} from 'vitest';
import {normalizeProduct} from '../src/catalog';
import {createBriefState,applyBriefOperations} from '../shared/briefState';
import type {BriefFactInput} from '../shared/briefSchema';
const mock=vi.hoisted(()=>({state:{} as any}));
vi.mock('../src/ShoppingProvider',()=>({useShopping:()=>mock.state}));
import {ProductWorkspace} from '../src/ProductWorkspace';
const pieces=[normalizeProduct({objectID:'a',Catalog_TitleDescription:'Necklace',Pricing_ActivePrice:54.99,Media_Images:['https://example.com/a.jpg']}),normalizeProduct({objectID:'b',Catalog_TitleDescription:'Ring',Pricing_ActivePrice:94.99,Media_Images:['https://example.com/b.jpg']})];
function budgetBrief(cents=15000,operator:'lt'|'lte'='lte',basis:'total'|'per-item'='total',extra:BriefFactInput[]=[]){const brief=createBriefState('workspace-budget');const fact:BriefFactInput={id:'budget',field:'budget',value:{kind:'money',cents,currency:'USD',operator,basis},scope:{kind:'mission'},strength:'requirement',status:'active',origin:'ui',evidence:{messageId:'manual',quote:'Manual budget',explicit:true,verified:true}};return applyBriefOperations(brief,{missionId:brief.missionId,expectedRevision:0,turnId:'manual',operations:[fact,...extra].map(fact=>({type:'add',fact}))});}
function state(view:string){return {brief:budgetBrief(),products:pieces.map(product=>({product,quantity:1})),selectionRecords:pieces,discoveries:[],displayIntro:'',activeView:view,compareIds:['a','b'],combinationIds:['a','b'],combinationQuantities:{a:1,b:1},budgetCents:15000,budgetScope:'total',refreshing:false,refreshError:'',setView:vi.fn(),refreshProducts:vi.fn(),toggleCompare:vi.fn(),toggleCombination:vi.fn(),pin:vi.fn(),remove:vi.fn(),setQuantity:vi.fn()};}
it('shows image-led comparison without subtotal or a chat submission button',()=>{mock.state=state('compare');const html=renderToStaticMarkup(<ProductWorkspace/>);expect(html).toContain('a.jpg');expect(html).toContain('b.jpg');expect(html).toContain('Not recorded');expect(html).not.toContain('Item subtotal');expect(html).not.toContain('Help me compare');});
it('calculates subtotal only for explicit combination selections',()=>{mock.state=state('combination');const html=renderToStaticMarkup(<ProductWorkspace/>);expect(html).toContain('$149.98');expect(html).toContain('$0.02');expect(html).toContain('Quantity');});
it('renders curated descriptions safely without literal markdown delimiters',()=>{mock.state={...state('discover'),displayIntro:'Choose **blue** <script>bad</script>',discoveries:[{title:'Options',items:[{product:pieces[0],why:'**Small** stone'}]}]};const html=renderToStaticMarkup(<ProductWorkspace/>);expect(html).not.toContain('Choose');expect(html).toContain('<strong>Small</strong>');expect(html).not.toContain('<script>');});

it('shows the exact per-item boundary conflict in combination view',()=>{mock.state={...state('combination'),brief:budgetBrief(9499,'lt','per-item'),budgetCents:9499,budgetScope:'per-item'};const html=renderToStaticMarkup(<ProductWorkspace/>);expect(html).toContain('An item conflicts with under $94.99 per item');expect(html).not.toContain('remains before other charges');});
it('shows foreign-budget uncertainty without turning an inclusive USD boundary into a violation',()=>{const foreign:BriefFactInput={id:'foreign',field:'budget',value:{kind:'money',cents:10000,currency:'GBP',operator:'lt',basis:'total'},scope:{kind:'mission'},strength:'requirement',status:'active',origin:'ui',evidence:{messageId:'foreign',quote:'GBP budget',explicit:true,verified:true}};mock.state={...state('combination'),brief:budgetBrief(14998,'lte','total',[foreign]),budgetCents:14998};const html=renderToStaticMarkup(<ProductWorkspace/>);expect(html).toContain('Budget currency GBP has no verified USD conversion');expect(html).not.toContain('Above your saved limit');expect(html).not.toContain('Combination conflicts');expect(html).not.toContain('remains before other charges');});
it('warns about a saved record conflicting with the only verified tentative budget',()=>{
 const initial=createBriefState('tentative-only');const brief=applyBriefOperations(initial,{missionId:initial.missionId,expectedRevision:0,turnId:'spoken-limit',operations:[{type:'add',fact:{id:'tentative-budget',field:'budget',value:{kind:'money',cents:5000,currency:'USD',operator:'lt',basis:'unresolved'},scope:{kind:'mission'},strength:'requirement',status:'tentative',origin:'spoken',evidence:{messageId:'spoken-limit',quote:'under $50',explicit:true,verified:true}}}]});
 mock.state={...state('saved'),brief,budgetCents:null};const html=renderToStaticMarkup(<ProductWorkspace/>);
 expect(html).toContain('Price conflicts with under $50.00');expect(html).toContain('Check against your brief');
});
