import {describe,it,expect} from 'vitest';
import {newShoppingState,pinRecord,restoreShoppingState,acceptShoppingProposal} from '../src/ShoppingProvider';
import {pairTotal} from '../shared/shopping';
const record=(id:string,price?:number)=>({objectID:id,Catalog_TitleDescription:`Piece ${id}`,Pricing_ActivePrice:price,Media_Images:['https://example.com/product.jpg']});
describe('persistent shopping workspace',()=>{
 it('keeps pinned record identity and exact observed price through a refresh',()=>{let state=pinRecord(newShoppingState(),record('variant-2',59.99));state={...state,compareIds:['variant-2'],budgetCents:15000};const restored=restoreShoppingState(JSON.stringify(state));expect(restored.missionId).toBe(state.missionId);expect(restored.products[0].product.id).toBe('variant-2');expect(restored.products[0].product.price).toBe(59.99);expect(restored.compareIds).toEqual(['variant-2']);expect(restored.budgetCents).toBe(15000)});
 it('does not duplicate a pinned variant or merge different variants',()=>{let state=pinRecord(newShoppingState(),record('a',10));state=pinRecord(state,record('a',11));state=pinRecord(state,record('b',12));expect(state.products).toHaveLength(2);expect(state.products[0].product.price).toBe(10)});
 it('rejects unsupported products and limits the shortlist',()=>{expect(()=>pinRecord(newShoppingState(),{title:'invented'})).toThrow();let state=newShoppingState();for(let i=0;i<12;i++)state=pinRecord(state,record(String(i),10));expect(()=>pinRecord(state,record('overflow',10))).toThrow(/12/)});
 it('resets mission state without inheriting selections or budget',()=>{const old=pinRecord(newShoppingState(),record('a',10));const fresh=newShoppingState();expect(fresh.missionId).not.toBe(old.missionId);expect(fresh.products).toEqual([]);expect(fresh.budgetCents).toBeNull();expect(fresh.facts).toEqual([])});
 it('discards broken or obsolete storage safely',()=>{expect(restoreShoppingState('not-json').products).toEqual([]);expect(restoreShoppingState(JSON.stringify({version:0,products:[record('a')]})).products).toEqual([])});
 it('preserves missing prices and calculates quantities with cents',()=>{expect(pairTotal([{price:90.24,quantity:1},{price:29.99,quantity:2}]).totalCents).toBe(15022);const unknown=pairTotal([{price:59.99},{price:null}]);expect(unknown.totalCents).toBeNull();expect(unknown.knownSubtotalCents).toBe(5999);expect(unknown.unknownCount).toBe(1)});
 it('retains dismissed proposal IDs within the current mission',()=>{const state={...newShoppingState(),dismissedIds:['old-preference']};expect(restoreShoppingState(JSON.stringify(state)).dismissedIds).toEqual(['old-preference']);expect(newShoppingState().dismissedIds).toEqual([])});
});

describe('brief correction and storage boundaries',()=>{
 it('rejects restored invented fields, sources and overlong values',()=>{const fact={id:'f',field:'material',value:'silver',quote:'silver',messageId:'m',status:'confirmed',source:'user-confirmed'};const state={...newShoppingState(),facts:[fact,{...fact,id:'badfield',field:'system'},{...fact,id:'badsource',source:'model'},{...fact,id:'toolong',value:'a'.repeat(301)},{...fact,id:'badmessage',messageId:0}]};expect(restoreShoppingState(JSON.stringify(state)).facts).toEqual([fact])});
 it('explicitly replacing a field removes superseded fact and keeps unrelated facts',()=>{const state=newShoppingState();state.facts=[{id:'old',field:'recipient',value:'wife',quote:'wife',messageId:'m1',status:'confirmed',source:'user-confirmed'},{id:'silver',field:'material',value:'silver',quote:'silver',messageId:'m1',status:'confirmed',source:'user-confirmed'}];state.proposals=[{id:'new',field:'recipient',value:'daughter',quote:'daughter',messageId:'m2',status:'proposed'}];const next=acceptShoppingProposal(state,'new');expect(next.facts.map(f=>f.value)).toEqual(['silver','daughter']);expect(next.dismissedIds).toContain('old');expect(next.proposals).toEqual([])});
 it('accepting a budget correction clears obsolete numeric budget',()=>{const state={...newShoppingState(),budgetCents:30000,proposals:[{id:'new',field:'budget' as const,value:'200 per item',quote:'200 per item',messageId:'m',status:'proposed' as const,scope:'per item'}]};const next=acceptShoppingProposal(state,'new');expect(next.budgetCents).toBeNull();expect(next.facts[0].scope).toBe('per item')});
 it('preserves sequential queued product updates',()=>{const updates=[(s:ReturnType<typeof newShoppingState>)=>pinRecord(s,record('a',20)),(s:ReturnType<typeof newShoppingState>)=>pinRecord(s,record('b',30))];const result=updates.reduce((state,update)=>update(state),newShoppingState());expect(result.products.map(p=>p.product.id)).toEqual(['a','b'])});
});
