import {useState,useEffect} from 'react';
import {useShopping,type PinnedProduct} from './ShoppingProvider';
import {type Product} from './catalog';
import {pairTotal} from '../shared/shopping';
import './product-workspace.css';
type View='discover'|'compare'|'saved'|'combination';
type Discovery={title:string;why?:string;items:{product:Product;why?:string}[]};
type ProductShopping={products:PinnedProduct[];discoveries:Discovery[];displayIntro:string;activeView:View;setView:(v:View)=>void;compareIds:string[];combinationIds:string[];toggleCompare:(id:string)=>void;toggleCombination:(id:string)=>void;pin:(raw:unknown)=>void;remove:(id:string)=>void;setQuantity:(id:string,n:number)=>void;refreshProducts:(ids:string[])=>Promise<void>;refreshing:boolean;refreshError:string;budgetCents:number|null;budgetScope:'total'|'per-item'};
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
function PlainText({text}:{text:string}){return <>{text.split(/(\*\*[^*]+\*\*)/g).map((part,i)=>part.startsWith('**')&&part.endsWith('**')?<strong key={i}>{part.slice(2,-2)}</strong>:part)}</>}
function ProductImage({product}:{product:Product}){const [failed,setFailed]=useState(false);return <div className="pw-image">{product.images[0]&&!failed?<img src={product.images[0]} alt={product.title} loading="lazy" onError={()=>setFailed(true)}/>:<span>Image unavailable</span>}</div>}
function Price({product}:{product:Product}){return <strong className="pw-price">{product.price===null?'Price unavailable':money(Math.round(product.price*100))}</strong>}
export function ProductWorkspace({onAsk}:{onAsk?:(text:string)=>void}){
 const raw=useShopping();const [previewId,setPreviewId]=useState<string|null>(null);
 useEffect(()=>{if(!previewId||!raw)return;const exists=raw.selectionRecords.some(p=>p.id===previewId)||raw.products.some(p=>p.product.id===previewId)||raw.discoveries.some(g=>g.items.some(i=>i.product.id===previewId));if(!exists)setPreviewId(null)},[previewId,raw?.selectionRecords,raw?.products,raw?.discoveries]);
 if(!raw)return null;
 // This view consumes the provider contract; the provider remains the sole state owner.
 const s=raw;
 const discoveries=s.discoveries??[];const view=s.activeView??'discover';const byId=new Map<string,Product>();s.selectionRecords.forEach(p=>byId.set(p.id,p));
 discoveries.forEach(g=>g.items.forEach(i=>byId.set(i.product.id,i.product)));s.products.forEach(p=>byId.set(p.product.id,p.product));
 const activePreview=previewId&&byId.has(previewId)?previewId:null;
 const selectedIds=view==='combination'?(s.combinationIds??[]):s.compareIds;
 const selected=selectedIds.flatMap(id=>{const product=byId.get(id);return product?[{product,quantity:s.combinationQuantities[id]??1}]:[]});
 const missing=selectedIds.filter(id=>!byId.has(id)).length;
 const totals=pairTotal(selected.map(p=>({price:p.product.price,quantity:p.quantity})));
 const over=s.budgetCents!==null&&(s.budgetScope==='total'?totals.knownSubtotalCents>s.budgetCents:selected.some(p=>p.product.price!==null&&Math.round(p.product.price*100)>s.budgetCents!));
 async function changeView(next:View){setPreviewId(null);s.setView(next);const ids=next==='compare'?s.compareIds:next==='combination'?(s.combinationIds??[]):next==='saved'?s.products.map(p=>p.product.id):[];if(ids.length)await s.refreshProducts(ids)}
 function actions(p:Product){const saved=s.products.some(x=>x.product.id===p.id);return <div className="pw-actions"><button onClick={()=>{setPreviewId(p.id);void s.refreshProducts([p.id])}}>View details</button><button aria-pressed={saved} onClick={()=>saved?s.remove(p.id):s.pin(p.raw)}>{saved?'Saved ✓':'Save piece'}</button><button aria-pressed={s.compareIds.includes(p.id)} disabled={!s.compareIds.includes(p.id)&&s.compareIds.length>=3} onClick={()=>s.toggleCompare(p.id)}>{s.compareIds.includes(p.id)?'Comparing ✓':'Compare'}</button><button aria-pressed={(s.combinationIds??[]).includes(p.id)} disabled={!s.combinationIds.includes(p.id)&&s.combinationIds.length>=3} onClick={()=>s.toggleCombination(p.id)}>{(s.combinationIds??[]).includes(p.id)?'In combination ✓':'Add to combination'}</button></div>}
 function tile(p:Product,why?:string){return <article className="pw-product" key={p.id}><ProductImage product={p}/><div className="pw-product-copy"><h3>{p.title}</h3><Price product={p}/>{why&&<p className="pw-why"><PlainText text={why}/></p>}<small>{p.inStock===true?'Listed in stock':p.inStock===false?'Listed unavailable':'Availability not recorded'}</small>{actions(p)}</div></article>}
 return <section className="product-workspace" aria-label="Shopping choices"><header className="pw-heading"><h2>Find your favourites</h2></header><nav className="pw-views" aria-label="Product views">{(['discover','compare','saved','combination'] as View[]).map(v=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>void changeView(v)}>{v==='discover'?'Discover':v==='compare'?`Compare${s.compareIds.length?` (${s.compareIds.length})`:''}`:v==='saved'?`Saved${s.products.length?` (${s.products.length})`:''}`:`Combination${s.combinationIds?.length?` (${s.combinationIds.length})`:''}`}</button>)}</nav>
 {s.refreshing&&<p className="pw-status" role="status">Checking the latest catalogue details…</p>}{s.refreshError&&<p className="pw-error" role="alert">{s.refreshError}</p>}
 {activePreview&&<section className="pw-preview" aria-label="Product preview"><button onClick={()=>setPreviewId(null)}>Back to choices</button><ProductImage product={byId.get(activePreview!)!}/><h3>{byId.get(activePreview!)!.title}</h3><Price product={byId.get(activePreview!)!}/><p>{byId.get(activePreview!)!.description}</p><dl>{byId.get(activePreview!)!.attributes.map(a=><div key={a.label}><dt>{a.label}</dt><dd>{a.value}</dd></div>)}</dl>{actions(byId.get(activePreview!)!)}</section>}
 {!activePreview&&view==='discover'&&<div className="pw-discover">{s.displayIntro&&<p className="pw-intro"><PlainText text={s.displayIntro}/></p>}{!discoveries.length?<div className="pw-empty"><h3>Let’s find your direction.</h3><p>Your concierge’s selections will appear here, with room to look closely and compare.</p></div>:discoveries.map((g,i)=><section className="pw-group" key={`${g.title}-${i}`}><h3>{g.title}</h3>{g.why&&<p><PlainText text={g.why}/></p>}<div className="pw-grid">{g.items.map(({product,why})=>tile(product,why))}</div></section>)}</div>}
 {!activePreview&&view==='saved'&&<div><p className="pw-intro">A place for the pieces you want to come back to.</p>{s.products.length?<div className="pw-grid">{s.products.map(({product})=>tile(product))}</div>:<div className="pw-empty"><h3>Something catch your eye?</h3><p>Save a piece from Discover or the catalogue. It will stay here while we explore.</p></div>}</div>}
 {!activePreview&&(view==='compare'||view==='combination')&&<div>{missing>0&&<p className="pw-error">{missing} selected piece{missing>1?'s need':' needs'} to be retrieved again before we can show a complete {view}.</p>}{!selected.length?<div className="pw-empty"><h3>{view==='compare'?'Which pieces are you deciding between?':'Build a combination you love.'}</h3><p>{view==='compare'?'Choose Compare on up to three pieces in Discover or Saved.':'Add pieces to a combination to see their item subtotal together.'}</p><button onClick={()=>s.setView('discover')}>Explore selections</button></div>:<>
 <p className="pw-intro"><PlainText text={view==='compare'?(s.comparisonIntro||'The details that make each piece different. A missing detail stays unknown.'):'Your selected pieces together. Quantities refer to catalogue items, which may themselves be sets.'}/></p><div className="pw-comparison" data-count={selected.length}>{selected.map(({product:p,quantity})=><article className="pw-compare-product" key={p.id}><ProductImage product={p}/><h3>{p.title}</h3><Price product={p}/>{view==='compare'?<dl>{[['Brand',p.brand],...['Material','Material purity','Gemstone shape','Gemstone dimensions'].map(label=>[label,p.attributes.find(a=>a.label===label)?.value])].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not recorded'}</dd></div>)}</dl>:<label className="pw-quantity">Quantity<select aria-label={`Quantity for ${p.title}`} value={quantity} onChange={e=>s.setQuantity(p.id,Number(e.target.value))}>{Array.from({length:10},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label>}<div className="pw-actions"><button onClick={()=>{setPreviewId(p.id);void s.refreshProducts([p.id])}}>View details</button><button onClick={()=>s.products.some(x=>x.product.id===p.id)?s.remove(p.id):s.pin(p.raw)}>{s.products.some(x=>x.product.id===p.id)?'Saved ✓':'Save piece'}</button></div><button onClick={()=>view==='compare'?s.toggleCompare(p.id):s.toggleCombination(p.id)}>Remove from {view==='compare'?'comparison':'combination'}</button></article>)}</div>
 {view==='combination'&&<div className="pw-subtotal"><span>{totals.totalCents===null||missing?'Known item subtotal':'Item subtotal'}</span><strong>{money(totals.knownSubtotalCents)}</strong>{(totals.unknownCount>0||missing>0)&&<p className="pw-error">The full total is unknown because a price or selected record is missing.</p>}{s.budgetCents!==null&&<p className={over?'pw-error':''}>{over?'Above your saved limit of':'Your saved limit:'} {money(s.budgetCents)} {s.budgetScope==='total'?'total':'per item'}.{!over&&!missing&&totals.totalCents!==null&&s.budgetScope==='total'?` ${money(s.budgetCents-totals.totalCents)} remains before other charges.`:''}</p>}</div>}
 <p className="pw-footnote">Catalogue prices and details can change. Taxes, shipping and any discounts need checking before purchase.</p></>}</div>}
 </section>
}
