import type {WorkspaceTraceBinding} from './telemetry';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {normalizeProduct,type Product} from './catalog';
import type {WorkspaceGroup,WorkspaceView} from './workspaceResults';
import {BRIEF_FIELDS,confirmProposal,type BriefFact,type BriefProposal} from '../shared/shopping';
import {createBriefState,applyBriefOperations as reduceBrief,undoBrief,migrateLegacyBrief} from '../shared/briefState';
import {briefStateSchema,type BriefState,type BriefOperation} from '../shared/briefSchema';
export const SHOPPING_STORAGE_KEY='jtv.shopping.v1';
export type PinnedProduct={product:Product;quantity:number;observedAt:string};
export type ShoppingState={version:1;missionId:string;brief:BriefState;displayTrace?:WorkspaceTraceBinding;discoveries:WorkspaceGroup[];displayIntro:string;comparisonIntro:string;activeView:WorkspaceView;displayRequest:number;combinationIds:string[];selectionRecords:Product[];combinationQuantities:Record<string,number>;notice?:string;facts:BriefFact[];proposals:BriefProposal[];dismissedIds:string[];products:PinnedProduct[];compareIds:string[];budgetCents:number|null;budgetScope:'total'|'per-item'};
export const newShoppingState=():ShoppingState=>{const missionId=crypto.randomUUID();return {version:1,missionId,brief:createBriefState(missionId),discoveries:[],displayIntro:'',comparisonIntro:'',activeView:'discover',displayRequest:0,combinationIds:[],selectionRecords:[],combinationQuantities:{},facts:[],proposals:[],dismissedIds:[],products:[],compareIds:[],budgetCents:null,budgetScope:'total'}};
export function restoreShoppingState(value:string|null):ShoppingState{
 try{const s=JSON.parse(value||'null');if(s?.version!==1||typeof s.missionId!=='string'||!s.missionId||s.missionId.length>100)return newShoppingState();
 const products=(Array.isArray(s.products)?s.products:[]).slice(0,12).flatMap((p:any)=>{try{return [{product:normalizeProduct(p.product.raw),quantity:Number.isInteger(p.quantity)&&p.quantity>=1&&p.quantity<=10?p.quantity:1,observedAt:typeof p.observedAt==='string'?p.observedAt:''}]}catch{return []}});
 const selectionRecords:Product[]=(Array.isArray(s.selectionRecords)?s.selectionRecords:[]).slice(0,6).flatMap((p:any)=>{try{return [normalizeProduct(p.raw)]}catch{return []}});
 const text=(v:unknown,max:number)=>typeof v==='string'&&v.trim().length>0&&v.length<=max;
 const validFact=(f:any)=>f&&text(f.id,20000)&&BRIEF_FIELDS.includes(f.field)&&text(f.value,300)&&text(f.quote,2000)&&text(f.messageId,200)&&(f.scope===undefined||text(f.scope,200));
 const parsed=briefStateSchema.safeParse(s.brief);let brief:BriefState;try{brief=parsed.success&&parsed.data.missionId===s.missionId&&(parsed.data.revision>0||(!(s.facts?.length)&&!(s.proposals?.length)))?parsed.data:migrateLegacyBrief(s.missionId,(Array.isArray(s.facts)?s.facts:[]).filter((f:any)=>validFact(f)&&f.status==='confirmed'&&(f.source==='user-confirmed'||f.source==='user-edited')),(Array.isArray(s.proposals)?s.proposals:[]).filter((f:any)=>validFact(f)&&f.status==='proposed'));}catch{brief=createBriefState(s.missionId)}
 if(!brief.facts.some(f=>f.status==='active'&&f.value.kind==='money')&&Number.isSafeInteger(s.budgetCents)&&s.budgetCents>=0&&s.budgetCents<=100000000){const fact=uiFact('budget',String(s.budgetCents/100));fact.value={kind:'money',cents:s.budgetCents,currency:'USD',operator:'lte',basis:s.budgetScope==='per-item'?'per-item':'total'};fact.strength='requirement';brief=reduceBrief(brief,{missionId:s.missionId,expectedRevision:brief.revision,turnId:'legacy-budget-migration',operations:[{type:'add',fact}]})}
 return {...newShoppingState(),brief,missionId:s.missionId,products,selectionRecords,combinationQuantities:Object.fromEntries(Object.entries(s.combinationQuantities??{}).filter(([id,n])=>selectionRecords.some(p=>p.id===id)&&Number.isInteger(n)&&Number(n)>=1&&Number(n)<=10).map(([id,n])=>[id,Number(n)])),dismissedIds:(Array.isArray(s.dismissedIds)?s.dismissedIds:[]).filter((id:unknown)=>typeof id==='string'&&id.length<=20000).slice(-100),facts:(Array.isArray(s.facts)?s.facts:[]).filter((f:any)=>validFact(f)&&f.status==='confirmed'&&(f.source==='user-confirmed'||f.source==='user-edited')).slice(0,40),proposals:(Array.isArray(s.proposals)?s.proposals:[]).filter((f:any)=>validFact(f)&&f.status==='proposed').slice(0,20),activeView:'saved',combinationIds:(Array.isArray(s.combinationIds)?s.combinationIds:[]).filter((id:string)=>(products.some((p:PinnedProduct)=>p.product.id===id)||selectionRecords.some(p=>p.id===id))).slice(0,3),compareIds:(Array.isArray(s.compareIds)?s.compareIds:[]).filter((id:string)=>(products.some((p:PinnedProduct)=>p.product.id===id)||selectionRecords.some(p=>p.id===id))).slice(0,3),budgetCents:Number.isSafeInteger(s.budgetCents)&&s.budgetCents>=0?s.budgetCents:null,budgetScope:s.budgetScope==='per-item'?'per-item':'total'};
 }catch{return newShoppingState()}
}
export function pinRecord(state:ShoppingState,raw:unknown):ShoppingState{
 const product=normalizeProduct(raw);if(state.products.some(p=>p.product.id===product.id))return state;
 if(state.products.length>=12)throw new Error('Your shortlist holds 12 pieces. Remove one before adding another.');
 return {...state,products:[...state.products,{product,quantity:1,observedAt:new Date().toISOString()}]};
}
/** Accept is explicitly labelled as replacement in the UI when that field already exists. */
export function acceptShoppingProposal(state:ShoppingState,id:string,replaceId?:string):ShoppingState {
 const p=state.proposals.find(p=>p.id===id);if(!p)return state;
 const previous=state.facts.filter(f=>f.id===replaceId);
 return {...state,...(p.field==='budget'?{budgetCents:null}:{}),facts:[...state.facts.filter(f=>f.id!==replaceId),confirmProposal(p)].slice(-40),dismissedIds:[...state.dismissedIds,...previous.map(f=>f.id)].slice(-100),proposals:state.proposals.filter(p=>p.id!==id)};
}
export type Shopping=ShoppingState&{hasDisplay:boolean;getBrief:()=>BriefState;acceptServerBrief:(next:BriefState,baseRevision:number,missionId:string)=>boolean;applyBriefOperations:(operations:BriefOperation[],expectedRevision?:number)=>boolean;undoBriefEdit:()=>boolean;refreshing:boolean;refreshError:string;openWorkspace:()=>void;setView:(view:WorkspaceView)=>void;setDiscoveries:(groups:WorkspaceGroup[],intro:string,binding?:{missionId:string;revision:number;trace?:WorkspaceTraceBinding})=>void;refreshProducts:(ids:string[])=>Promise<void>;toggleCombination:(id:string)=>void;error:string;pin:(raw:unknown)=>void;remove:(id:string)=>void;setQuantity:(id:string,n:number)=>void;toggleCompare:(id:string)=>void;setBudget:(cents:number|null,scope:'total'|'per-item')=>void;addProposals:(p:BriefProposal[],missionId:string)=>void;acceptProposal:(id:string,replaceId?:string)=>void;rejectProposal:(id:string)=>void;editFact:(id:string,value:string)=>void;removeFact:(id:string)=>void;addFact:(field:BriefFact['field'],value:string)=>void;resetMission:()=>void;getContext:()=>Record<string,unknown>};
const Context=createContext<Shopping|null>(null);
export function useShopping(){return useContext(Context)}
export function ShoppingProvider({children}:{children:ReactNode}){
 const [state,setState]=useState<ShoppingState>(()=>{try{return restoreShoppingState(sessionStorage.getItem(SHOPPING_STORAGE_KEY))}catch{return newShoppingState()}});
 const [error,setError]=useState('');const [refreshing,setRefreshing]=useState(false);const [refreshError,setRefreshError]=useState('');const latest=useRef(state);latest.current=state;
 useEffect(()=>{try{sessionStorage.setItem(SHOPPING_STORAGE_KEY,JSON.stringify(state))}catch{setError('Your shortlist is available now, but this browser could not save it for a refresh.')}},[state]);
 const commit=(next:ShoppingState)=>{latest.current=next;setState(next)};
 const applyOperations=(operations:BriefOperation[],expectedRevision=latest.current.brief.revision)=>{try{const current=latest.current;const brief=reduceBrief(current.brief,{missionId:current.missionId,expectedRevision,turnId:crypto.randomUUID(),operations});commit(withBrief(current,brief));return true}catch{setError('Your brief changed while this edit was open. Please try the edit again.');return false}};
 const value:Shopping={...state,refreshing,refreshError,
 hasDisplay:state.discoveries.some(g=>g.items.length>0)||(state.displayRequest>0&&(state.products.length>0||state.selectionRecords.length>0)),
 getBrief(){return latest.current.brief},
 acceptServerBrief(next,baseRevision,missionId){const current=latest.current;const parsed=briefStateSchema.safeParse(next);if(!parsed.success||current.missionId!==missionId||current.brief.revision!==baseRevision||parsed.data.revision<baseRevision||parsed.data.missionId!==missionId)return false;commit(withBrief(current,parsed.data));return true},
 applyBriefOperations:applyOperations,
 undoBriefEdit(){try{const current=latest.current;if(!current.brief.events.length)return false;commit(withBrief(current,undoBrief(current.brief,current.brief.revision)));return true}catch{return false}},
 openWorkspace(){setState(s=>({...s,displayRequest:s.displayRequest+1}))},
 setView(activeView){setState(s=>({...s,activeView}))},
 setDiscoveries(discoveries,displayIntro,binding){setState(s=>{if(binding&&(s.missionId!==binding.missionId||s.brief.revision!==binding.revision))return {...s,notice:'These choices came from an earlier brief. Ask the concierge to refresh them.'};const records=discoveries.flatMap(g=>g.items.map(i=>i.product));const update=(p:Product)=>records.find(r=>r.id===p.id)??p;const comparing=s.activeView==='compare'&&s.compareIds.length>0&&records.every(r=>s.compareIds.includes(r.id));return {...s,discoveries,displayTrace:binding?.trace,displayIntro,comparisonIntro:comparing?displayIntro:s.comparisonIntro,activeView:comparing?'compare':'discover',selectionRecords:s.selectionRecords.map(update),products:s.products.map(p=>({...p,product:update(p.product),observedAt:records.some(r=>r.id===p.product.id)?new Date().toISOString():p.observedAt}))}})},
 toggleCombination(id){setState(s=>{const product=s.selectionRecords.find(p=>p.id===id)??s.products.find(p=>p.product.id===id)?.product??s.discoveries.flatMap(g=>g.items).find(i=>i.product.id===id)?.product;if(!product)return s;const ids=s.combinationIds.includes(id)?s.combinationIds.filter(x=>x!==id):s.combinationIds.length<3?[...s.combinationIds,id]:s.combinationIds;return {...s,combinationIds:ids,selectionRecords:[...s.selectionRecords.filter(p=>p.id!==id),product].filter(p=>ids.includes(p.id)||s.compareIds.includes(p.id))}})},
 async refreshProducts(ids){const mission=latest.current.missionId;setRefreshing(true);setRefreshError('');try{const records=await Promise.all([...new Set(ids)].slice(0,12).map(async id=>{const r=await fetch(`/api/products/${encodeURIComponent(id)}`);if(!r.ok)throw new Error('Some details could not be refreshed. Previously saved information is still shown.');const product=normalizeProduct(await r.json());if(product.id!==id)throw new Error('The returned product identity did not match.');return product}));if(latest.current.missionId!==mission)return;setState(s=>{if(s.missionId!==mission)return s;const updated=(p:Product)=>records.find(r=>r.id===p.id)??p;return {...s,selectionRecords:s.selectionRecords.map(updated),products:s.products.map(p=>({...p,product:updated(p.product),observedAt:records.some(r=>r.id===p.product.id)?new Date().toISOString():p.observedAt})),discoveries:s.discoveries.map(g=>({...g,items:g.items.map(i=>({...i,product:updated(i.product)}))}))}})}catch(e){if(latest.current.missionId===mission)setRefreshError(e instanceof Error?e.message:'Could not refresh products.')}finally{if(latest.current.missionId===mission)setRefreshing(false)}},
 error:state.notice||error,
 pin(raw){setState(s=>{try{return {...pinRecord(s,raw),notice:''}}catch(e){return {...s,notice:e instanceof Error?e.message:'This product could not be saved.'}}})},
 remove(id){setState(s=>({...s,products:s.products.filter(p=>p.product.id!==id)}))},
 setQuantity(id,n){if(Number.isInteger(n)&&n>=1&&n<=10)setState(s=>({...s,combinationQuantities:{...s.combinationQuantities,[id]:n},products:s.products.map(p=>p.product.id===id?{...p,quantity:n}:p)}))},
 toggleCompare(id){setState(s=>{const product=s.selectionRecords.find(p=>p.id===id)??s.products.find(p=>p.product.id===id)?.product??s.discoveries.flatMap(g=>g.items).find(i=>i.product.id===id)?.product;if(!product)return s;const ids=s.compareIds.includes(id)?s.compareIds.filter(x=>x!==id):s.compareIds.length<3?[...s.compareIds,id]:s.compareIds;return {...s,compareIds:ids,comparisonIntro:'',selectionRecords:[...s.selectionRecords.filter(p=>p.id!==id),product].filter(p=>ids.includes(p.id)||s.combinationIds.includes(p.id))}})},
 setBudget(cents,scope){if(cents!==null&&(!Number.isSafeInteger(cents)||cents<0))return;const ids=latest.current.brief.facts.filter(f=>f.field==='budget'&&f.status==='active').map(f=>f.id);if(cents===null){if(ids.length)applyOperations([{type:'retract',factIds:ids}]);return}const fact=uiFact('budget',`${cents/100}`);fact.value={kind:'money',cents,currency:'USD',operator:'lte',basis:scope};fact.strength='requirement';applyOperations([ids.length?{type:'replace',factIds:ids,fact}:{type:'add',fact}])},
 addProposals(proposals,missionId){setState(s=>s.missionId!==missionId?s:{...s,proposals:proposals.filter(p=>!s.dismissedIds.includes(p.id)&&!s.facts.some(f=>f.id===p.id)).slice(-20)})},
 acceptProposal(id,replaceId){setState(s=>acceptShoppingProposal(s,id,replaceId))},
 rejectProposal(id){setState(s=>({...s,dismissedIds:[...s.dismissedIds,id].slice(-100),proposals:s.proposals.filter(p=>p.id!==id)}))},
 editFact(id,value){const previous=latest.current.brief.facts.find(f=>f.id===id);if(previous&&value.trim())applyOperations([{type:'replace',factIds:[id],fact:{...uiFact(previous.field,value),scope:previous.scope,strength:previous.strength}}])},
 removeFact(id){applyOperations([{type:'retract',factIds:[id]}])},
 addFact(field,value){if(value.trim())applyOperations([{type:'add',fact:uiFact(field,value)}])},
 resetMission(){const current=latest.current;const fresh=newShoppingState();commit({...fresh,products:current.products,selectionRecords:current.selectionRecords,compareIds:current.compareIds,combinationIds:current.combinationIds,combinationQuantities:current.combinationQuantities,notice:current.products.length?'Saved pieces are retained. Check them against your new brief.':''});setError('');setRefreshing(false);setRefreshError('')},
 getContext(){const s=latest.current;return {missionId:s.missionId,brief:{missionId:s.brief.missionId,revision:s.brief.revision,facts:s.brief.facts.filter(f=>f.status==='active').map(({field,value,scope,strength})=>({field,value,scope,strength}))},confirmedBrief:s.facts.map(({field,value,source,scope,messageId})=>({field,value,source,scope,messageId})),budget:s.budgetCents===null?null:{amount:s.budgetCents/100,currency:'USD',scope:s.budgetScope,source:'explicit UI entry'},shortlist:s.products.map(({product:p,quantity})=>({objectID:p.id,quantity})),shortlistEvidence:'Saved selections only. Retrieve current product evidence before making claims.',comparisonIds:s.compareIds,combination:s.combinationIds.map(objectID=>({objectID,quantity:s.combinationQuantities[objectID]??1})),displayedProductIds:s.discoveries.flatMap(g=>g.items.map(i=>i.product.id))}}
 };
 return <Context.Provider value={value}>{children}</Context.Provider>
}

export function uiFact(field:BriefFact['field'],text:string):import('../shared/briefSchema').BriefFactInput{return {id:crypto.randomUUID(),field,value:{kind:'text',text:text.trim().slice(0,300)},scope:{kind:'mission'},strength:'preference',status:'active',origin:'ui',evidence:{messageId:`ui-${crypto.randomUUID()}`,quote:text.trim().slice(0,300),explicit:true,verified:true}}}
export function withBrief(state:ShoppingState,brief:BriefState):ShoppingState{
 const active=brief.facts.filter(f=>f.status==='active');const budget=[...active].reverse().find(f=>f.value.kind==='money');const value=budget?.value;
 return {...state,brief,missionId:brief.missionId,facts:active.map(f=>({id:f.id,field:f.field,value:f.value.kind==='text'?f.value.text:f.value.kind==='money'?`${f.value.operator==='lt'?'Under':'Up to'} $${(f.value.cents/100).toFixed(2)}`:f.value.values.join(', '),quote:f.evidence.quote,messageId:f.evidence.messageId,status:'confirmed',source:f.origin==='ui'?'user-edited':'user-confirmed',scope:f.scope.kind==='mission'?undefined:f.scope.key})),budgetCents:value?.kind==='money'&&value.basis!=='unresolved'?value.cents:null,budgetScope:value?.kind==='money'&&value.basis==='per-item'?'per-item':'total'};
}
