import {useEffect,useState} from 'react';
import {useShopping} from './ShoppingProvider';
import {BRIEF_FIELDS,type BriefField,pairTotal} from '../shared/shopping';
import './shopping-workspace.css';
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export function ShoppingWorkspace({onSend,onReset}:{onSend?:(message:string)=>void;onReset?:()=>void}){
 const s=useShopping();const [budget,setBudget]=useState('');const [scope,setScope]=useState<'total'|'per-item'>('total');const [budgetError,setBudgetError]=useState('');const [editing,setEditing]=useState<string|null>(null);const [draft,setDraft]=useState('');const [manual,setManual]=useState('');const [field,setField]=useState<BriefField>('other');
 useEffect(()=>{setBudget(s?.budgetCents==null?'':(s.budgetCents/100).toFixed(2));setScope(s?.budgetScope??'total')},[s?.budgetCents,s?.budgetScope,s?.missionId]);
 if(!s)return null;
 const selected=s.products.filter(p=>s.compareIds.includes(p.product.id));const totals=pairTotal(selected.map(p=>({price:p.product.price,quantity:p.quantity})));
 const overBudget=s.budgetCents!==null&&(s.budgetScope==='total'?totals.knownSubtotalCents>s.budgetCents:selected.some(p=>p.product.price!==null&&Math.round(p.product.price*100)>s.budgetCents!));
 function saveBudget(e:React.FormEvent){e.preventDefault();if(!budget.trim()){setBudgetError('Enter an amount, or use Clear budget to remove the limit.');return}if(!/^\d+(\.\d{1,2})?$/.test(budget)||Number(budget)>10000000){setBudgetError('Enter a valid dollar amount with up to two decimal places.');return}s!.setBudget(Math.round(Number(budget)*100),scope);setBudgetError('')}
 return <aside className="shopping-workspace" aria-label="Your shopping workspace">
  <header className="workspace-heading"><div><span className="workspace-eyebrow">A LITTLE ROOM TO CHOOSE</span><h2>Your shortlist</h2><p>Keep the pieces you like. We’ll work from here.</p></div><span className="workspace-count">{s.products.length}/12</span></header>
  {s.error&&<p role="alert" className="workspace-error">{s.error}</p>}
  {!s.products.length?<div className="workspace-empty"><h3>Something catch your eye?</h3><p>Use the heart on a product to keep it here. Your choices stay while we explore.</p></div>:<div className="shortlist-grid">{s.products.map(({product:p,quantity,observedAt})=><article key={p.id} className="shortlist-item">
   <div className="shortlist-image">{p.images[0]?<img src={p.images[0]} alt={p.title} loading="lazy" onError={e=>{e.currentTarget.hidden=true}}/>:<span>Image unavailable</span>}</div><div className="shortlist-copy"><h3>{p.title}</h3><strong>{p.price===null?'Price unavailable':money(Math.round(p.price*100))}</strong><small>Item {p.id}</small><small>{p.inStock===false?'Listed unavailable':p.inStock===true?'Listed in stock':'Availability unverified'}</small><small>Saved {observedAt?new Date(observedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'earlier'}. Recheck price before buying.</small>
   <div className="shortlist-controls"><label className="compare-toggle"><input type="checkbox" checked={s.compareIds.includes(p.id)} disabled={!s.compareIds.includes(p.id)&&s.compareIds.length>=3} onChange={()=>s.toggleCompare(p.id)}/>Compare / pair</label><button onClick={()=>s.remove(p.id)} aria-label={`Remove ${p.title} from shortlist`}>Remove</button></div>
   {s.compareIds.includes(p.id)&&<label className="quantity-control">Quantity <select aria-label={`Quantity for ${p.title}`} value={quantity} onChange={e=>s.setQuantity(p.id,Number(e.target.value))}>{Array.from({length:10},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label>}
   </div></article>)}</div>}
  {!!selected.length&&<section className="workspace-comparison" aria-label="Selected comparison"><h3>Your combination</h3><p>{selected.length} selected piece{selected.length>1?'s':''}. Select up to three to compare or pair.</p><dl>{selected.map(({product:p,quantity})=><div key={p.id}><dt>{p.title} × {quantity}</dt><dd>{p.price===null?'Unknown':money(Math.round(p.price*100)*quantity)}</dd></div>)}<div className="combination-total"><dt>{totals.totalCents===null?'Known subtotal':'Item subtotal'}</dt><dd>{money(totals.knownSubtotalCents)}</dd></div></dl>{totals.unknownCount>0&&<p className="workspace-error">{totals.unknownCount} price{totals.unknownCount>1?'s are':' is'} missing. The full total is unknown.</p>}<details className="comparison-facts"><summary>Compare catalogue details</summary><div className="comparison-facts-grid">{selected.map(({product:p})=><article key={p.id}><h4>{p.title}</h4><dl>{['Material','Material purity','Gemstone shape','Gemstone dimensions'].map(label=><div key={label}><dt>{label}</dt><dd>{p.attributes.find(a=>a.label===label)?.value||'Not recorded'}</dd></div>)}</dl></article>)}</div></details><p className="workspace-note">Recorded item prices only. Tax, shipping, discounts and current availability need checking.</p>{s.budgetCents!==null&&<p className={overBudget?'workspace-error':'workspace-note'}>{overBudget?'This selection exceeds':'Your limit is'} {money(s.budgetCents)} {s.budgetScope==='total'?'in total':'per item'}.{!overBudget&&s.budgetScope==='total'&&totals.totalCents!==null?` ${money(s.budgetCents-totals.totalCents)} remains before any other charges.`:''}</p>}{onSend&&<button className="primary-button" onClick={()=>onSend(`Compare my selected catalogue items ${selected.map(p=>p.product.id).join(', ')} against my current preferences. Refresh their evidence and explain useful differences and anything unknown.`)}>Help me compare these</button>}</section>}
  <details className="shopping-brief" open><summary>What we’re looking for</summary><p className="workspace-note">Confirm suggestions before they become requirements. You can change your mind.</p>
  {s.facts.map(f=><div className="brief-fact" key={f.id}>{editing===f.id?<form onSubmit={e=>{e.preventDefault();if(draft.trim()){s.editFact(f.id,draft);setEditing(null)}}}><label>{f.field}<input maxLength={300} value={draft} onChange={e=>setDraft(e.target.value)} autoFocus/></label><button type="submit">Save preference</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></form>:<><span><b>{f.field}</b>: {f.value}</span><div><button onClick={()=>{setEditing(f.id);setDraft(f.value)}} aria-label={`Edit ${f.field}: ${f.value}`}>Edit</button><button onClick={()=>s.removeFact(f.id)} aria-label={`Remove preference ${f.value}`}>Remove</button></div></>}</div>)}
  {!s.facts.length&&<p>No confirmed preferences yet. Tell the concierge what you have in mind.</p>}
  {s.proposals.map(p=><div className="brief-proposal" key={p.id}><strong>Did I understand this?</strong>{s.facts.some(f=>f.field===p.field)&&<p className="workspace-note">This would replace: {s.facts.filter(f=>f.field===p.field).map(f=>f.value).join('; ')}.</p>}<p>{p.field}: {p.value}{p.scope?` (${p.scope})`:''}</p>{p.field==='budget'&&s.budgetCents!==null&&<p className="workspace-note">Accepting replaces your saved {money(s.budgetCents)} {s.budgetScope} budget. Enter the new amount below to calculate remaining budget.</p>}<blockquote>“{p.quote}”</blockquote><div><button onClick={()=>s.acceptProposal(p.id)}>{s.facts.some(f=>f.field===p.field)?`Replace previous ${p.field}`:'Yes, keep this'}</button><button onClick={()=>s.rejectProposal(p.id)}>Not quite</button></div></div>)}
  <form className="manual-brief" onSubmit={e=>{e.preventDefault();if(manual.trim()){s.addFact(field,manual);setManual('')}}}><label>Preference type<select value={field} onChange={e=>setField(e.target.value as BriefField)}>{BRIEF_FIELDS.map(f=><option key={f} value={f}>{f}</option>)}</select></label><label>Add a preference<input value={manual} maxLength={300} onChange={e=>setManual(e.target.value)} placeholder="Something important to you"/></label>{s.facts.some(f=>f.field===field)&&<p className="workspace-note">Saving replaces your existing {field} preference.</p>}<button type="submit" disabled={!manual.trim()}>{s.facts.some(f=>f.field===field)?'Replace preference':'Add preference'}</button></form>
  <form className="budget-form" onSubmit={saveBudget}><label>Budget (USD)<input inputMode="decimal" placeholder={s.budgetCents===null?'Add a limit':(s.budgetCents/100).toFixed(2)} value={budget} onChange={e=>setBudget(e.target.value)} aria-describedby="budget-help"/></label><label>Applies to<select value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="total">Whole combination</option><option value="per-item">Each item</option></select></label><button type="submit">Save budget</button>{s.budgetCents!==null&&<button type="button" onClick={()=>{s.setBudget(null,scope);setBudget('')}}>Clear budget</button>}<small id="budget-help">{s.budgetCents!==null?`Saved: ${money(s.budgetCents)} ${s.budgetScope==='total'?'total':'per item'}. `:''}Item prices; other charges may apply.</small>{budgetError&&<p role="alert" className="workspace-error">{budgetError}</p>}</form>
  </details>
  {onReset&&<footer className="workspace-reset"><button onClick={onReset}>Start a new shopping mission</button></footer>}
 </aside>
}
